<?php 
return [
    'Diamondbacks' => 'Arizona Diamondbacks',
    'Braves'       => 'Atlanta Braves',
    'Orioles'      => 'Baltimore Orioles',
    'Red Sox'      => 'Boston Red Sox',
    'Cubs'         => 'Chicago Cubs',
    'White Sox'    => 'Chicago White Sox',
    'Reds'         => 'Cincinnati Reds',
    'Guardians'    => 'Cleveland Guardians',
    'Rockies'      => 'Colorado Rockies',
    'Tigers'       => 'Detroit Tigers',
    'Astros'       => 'Houston Astros',
    'Royals'       => 'Kansas City Royals',
    'Angels'       => 'Los Angeles Angels',
    'Dodgers'      => 'Los Angeles Dodgers',
    'Marlins'      => 'Miami Marlins',
    'Brewers'      => 'Milwaukee Brewers',
    'Twins'        => 'Minnesota Twins',
    'Mets'         => 'New York Mets',
    'Yankees'      => 'New York Yankees',
    'Athletics'    => 'Oakland Athletics',
    'Phillies'     => 'Philadelphia Phillies',
    'Pirates'      => 'Pittsburgh Pirates',
    'Padres'       => 'San Diego Padres',
    'Giants'       => 'San Francisco Giants',
    'Mariners'     => 'Seattle Mariners',
    'Cardinals'    => 'St. Louis Cardinals',
    'Rays'         => 'Tampa Bay Rays',
    'Rangers'      => 'Texas Rangers',
    'Blue Jays'    => 'Toronto Blue Jays',
    'Nationals'    => 'Washington Nationals',
    'Free Agents'   => 'Free Agents'
];